github: [franciskamande-ai]  # Your GitHub username
buy_me_a_coffee: franciskamande  
custom: 
  - "https://fknlabs.netlify.app"  
  - "https://franciskamande.netlify.app"  
  - "mailto:fkamande264@gmail.com?subject=FinexaGPT%20Sponsorship"  
  - "https://buymeacoffee.com/franciskamande"  
